---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flm
spec:
  replicas: 3
  selector:
    matchLabels:
      app: swiggy
      env: blue
  template:
    metadata:
      labels:
        app: swiggy
        env: blue
    spec:
      containers:
        - name: comt-1
          image: kamalreddyy/sushma:v1
          ports:
          - containerPort: 3000
