---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flm
spec:
  replicas: 3
  selector:
    matchLabels:
      app: swiggy
      env: green
  template:
    metadata:
      labels:
        app: swiggy
        env: green
    spec:
      containers:
        - name: comt-1
          image: kamalreddyy/newrepo:v2
          ports:
          - containerPort: 3000
